pub(crate) mod components;
pub(crate) mod effects;
pub(crate) mod helpers {
    pub(crate) use crate::helpers::*;
}
mod spawn;
mod systems;

use bevy::prelude::*;
pub(crate) use spawn::{
    cleanup_runtime_entities,
    log_runtime_hostile_scene_summary,
    runtime_scene_missing,
    runtime_scene_present,
    ship_visual_center,
    spawn_runtime_scene,
    spawn_ship_layer_visuals,
};
pub(crate) use systems::{
    advance_projectiles,
    aim_hostile_turrets,
    apply_module_interactions,
    apply_player_environmental_effects,
    apply_player_ship_controls,
    begin_held_interactions,
    camera_follow_player_ship,
    collect_salvage,
    complete_held_interactions,
    detect_nearby_interactions,
    draw_debug_overlay,
    drive_hostile_ships,
    exit_focused_station,
    fire_hostile_ship_weapons,
    fire_hostile_targets,
    fire_player_weapons,
    handle_player_cargo_interaction,
    handle_projectile_hits,
    handle_ship_collisions,
    integrate_hostile_ship_motion,
    integrate_player_ship_motion,
    move_shipboard_player,
    rebuild_infrastructure_networks,
    return_after_mission_resolution,
    return_button_system,
    return_keyboard_shortcut,
    run_arch_automation,
    run_drone_logistics,
    run_logistics_transfers,
    run_processors,
    run_shipboard_interaction_input,
    sample_player_atmosphere,
    sample_ship_fields,
    spawn_missing_effect_overlays,
    station_panel_button_system,
    sync_backdrop_parallax,
    sync_battery_pulse_visuals,
    sync_crew_name_labels,
    sync_drone_station_population,
    sync_engine_flame_visuals,
    sync_eva_thruster_visuals,
    sync_fabricator_dust_visuals,
    sync_hazard_effect_visuals,
    sync_hostile_ship_state,
    sync_module_work_effect_visuals,
    sync_player_reference_frame_parenting,
    sync_reactor_glow_visuals,
    sync_runtime_ship_state,
    sync_service_link_visuals,
    sync_ship_environment_effect_visuals,
    sync_shipboard_player_visual,
    sync_turret_flash_visuals,
    tick_recent_action_feedback,
    toggle_gameplay_info_panel,
    update_current_station,
    update_destroyed_module_visuals,
    update_detector_modules,
    update_gameplay_status_text,
    update_mission_state,
    update_mission_telemetry,
    update_module_runtime_state,
    update_player_focused_tiles,
    update_player_reference_frame,
    update_routed_ship_power,
    update_ship_atmosphere,
    update_station_command_input,
};

const RUNTIME_SHIP_ORIGIN: Vec3 = Vec3::new(0.0, -2200.0, 10.0);
pub(crate) const ARENA_WIDTH_TILES: i32 = 240;
pub(crate) const ARENA_HEIGHT_TILES: i32 = 160;
