use super::*;

#[derive(Clone, Copy)]
pub(crate) struct ArchSnapshot {
    pub(crate) ship_power_reserve: Fx,
    pub(crate) ship_average_heat: Fx,
    pub(crate) mission_threat: Fx,
    pub(crate) reactor_reaction_rate: Fx,
    pub(crate) reactor_turbine_load: Fx,
    pub(crate) reactor_heat: Fx,
    pub(crate) reactor_instability: Fx,
    pub(crate) reactor_power_output: Fx,
    pub(crate) storage_raw_salvage: Fx,
    pub(crate) storage_repair_charge: Fx,
    pub(crate) processor_raw_salvage: Fx,
    pub(crate) processor_repair_charge: Fx,
    pub(crate) turret_ready: Fx,
    pub(crate) turret_cooldown: Fx,
    pub(crate) turret_desired_angle: Fx,
    pub(crate) turret_actual_angle: Fx,
    pub(crate) life_friendly_present: Fx,
    pub(crate) life_hostile_present: Fx,
    pub(crate) life_dir_x: Fx,
    pub(crate) life_dir_y: Fx,
    pub(crate) life_distance: Fx,
    pub(crate) ship_nearby_present: Fx,
    pub(crate) ship_hostile_present: Fx,
    pub(crate) ship_dir_x: Fx,
    pub(crate) ship_dir_y: Fx,
    pub(crate) ship_distance: Fx,
    pub(crate) damage_incoming: Fx,
    pub(crate) damage_critical: Fx,
    pub(crate) damage_dir_x: Fx,
    pub(crate) damage_dir_y: Fx,
    pub(crate) damage_intensity: Fx,
    pub(crate) power_deficit: Fx,
    pub(crate) power_low_battery: Fx,
    pub(crate) heat_alert: Fx,
    pub(crate) heat_dir_x: Fx,
    pub(crate) heat_dir_y: Fx,
    pub(crate) heat_severity: Fx,
    pub(crate) logistics_demand: Fx,
    pub(crate) logistics_dir_x: Fx,
    pub(crate) logistics_dir_y: Fx,
    pub(crate) logistics_severity: Fx,
    pub(crate) junction_open: Fx,
    pub(crate) junction_powered: Fx,
    pub(crate) junction_supply: Fx,
    pub(crate) junction_demand: Fx,
    pub(crate) valve_open: Fx,
    pub(crate) valve_powered: Fx,
    pub(crate) valve_supply: Fx,
    pub(crate) valve_demand: Fx,
}

#[derive(Default)]
pub(crate) struct PendingArchCommands {
    pub(crate) reactor_bias: Fx,
    pub(crate) logistics_enabled: bool,
    pub(crate) logistics_preference: ArchLogisticsPreference,
    pub(crate) turret_assist: bool,
    pub(crate) turret_auto_fire: bool,
    pub(crate) turret_fire_hold: bool,
    pub(crate) junction_open: Option<bool>,
    pub(crate) valve_open: Option<bool>,
}

#[derive(Clone, Copy, Default)]
pub(crate) struct LumenSnapshot {
    pub(crate) reactor_count: u32,
    pub(crate) turret_count: u32,
    pub(crate) cargo_count: u32,
    pub(crate) processor_count: u32,
    pub(crate) computer_count: u32,
    pub(crate) hot_module_count: u32,
    pub(crate) threat_present: bool,
    pub(crate) low_power: bool,
}
