use bevy::{
    ecs::{relationship::Relationship, system::SystemParam},
    prelude::*,
};

use crate::{
    balance::BalanceConfig,
    gameplay::{
        components::{
            AirlockCommandState,
            AngularVelocity,
            CarriedResource,
            CurrentStation,
            DestroyedModule,
            HostileShip,
            HostileTarget,
            Integrity,
            LinearVelocity,
            ManipulatorCommandState,
            ManipulatorModule,
            MissionState,
            ModuleCondition,
            ModuleRuntimeState,
            ObservedLocalPlayerMarker,
            PlayerFieldState,
            PlayerMotionState,
            PlayerReferenceFrame,
            PlayerShip,
            ProcessorCommandState,
            ProcessorModule,
            Projectile,
            ReactorCommandState,
            RuntimeArchComputer,
            RuntimeShipModule,
            ShipAutomationState,
            ShipAtmosphereState,
            ShipControlMode,
            ShipControlState,
            ShipMovementModel,
            ShipPowerModel,
            ShipPowerState,
            ShipRoot,
            ShipWeaponState,
            ShipboardControlState,
            SimPosition,
            StorageCommandState,
            StorageModule,
            TurretCommandState,
        },
        helpers::{
            Fx,
            danger_level,
            format_fx0,
            format_fx1,
            format_fx2,
            mission_return_line,
            mission_status_line,
            module_condition,
            resource_kind_label,
        },
        systems::shared::module_display_name,
    },
    netcode,
    state::{
        DebugOverlayState,
        DemoProgression,
        GameplayBarFill,
        GameplayBarKind,
        GameplayBarLabel,
        GameplayCompactStatusText,
        GameplayControlsText,
        GameplayPanelBodyText,
        GameplayPanelTitleText,
        GameplayStationPanel,
        GameplayStationPanelButton,
        GameplayStationPanelButtonLabel,
        GameplayTopBannerText,
        StationPanelButtonAction,
    },
};

mod hud;
mod station_panel;
mod summary;

pub(crate) use hud::update_gameplay_status_text;
pub(crate) use station_panel::station_panel_button_system;
